### ISSUE TITLE
Making the signature for mapDispatch more similar to the mapState signature

### ISSUE THREAD

**Issue by brainlessdeveloper** [edvincandon/revux#1]
Hi there!

Thanks for this little library. I couldn't manage to make Revue or vue-redux work. I'm curious as to why you chose to expect different things for `mapDispatch` and `mapState`.

Would it be a good idea to also expec an object for `mapState`? I'd be more comfortable with something like this:

```
const mapState = {
  todos: state => state.todos.index,
  todo: state => state.todos.single,
}
const mapDispatch = {
  addTodo: todoActions.create,
}

connect(mapState, mapDispatch)(AwesomeComponent)
```

This is an issue mostly about aesthetics and consistence. The API works perfectly as-is.

**Comment by edvincandon** [comment]
Hey, I'm gonna make a quick release today to support passing `mapState` as an object and not necessarily as a function.

Will let you know :) 
Thanks for the feedback

**Comment by brainlessdeveloper** [comment]
Would that be an API change or an extension? I.e. would the library support both an object and a function?

**Comment by edvincandon** [comment]
Yes both of course! I'll just check `typeof mapState` and handle both cases

**Comment by edvincandon** [comment]
@brainlessdeveloper 
Are you sure you can pass an object to mapStateToProps in react-redux? I can't find any documentation.

**Comment by brainlessdeveloper** [comment]
No you can't - I'm sorry, the title is kind of confusing.

My suggestion was to make the API for `mapState` and `mapDispatch` equal (i.e. takes an object) for consistency.

I'll change the title.

**Comment by edvincandon** [comment]
Okay, would you need to handle deeply nested state:
```
const mapState = {
    foo: {
        bar: state => state.foo.bar
        baz: {
           bar: state => state.foo.baz.bar
        }
    }
}
```

But then again, writing such a ```mapState``` is bad practice.
I'll have to think about it.

**Comment by brainlessdeveloper** [comment]
I agree - it's bad practice. But with a shallow object, you could still nest your result like this (even if it's bad practice):

```
const mapState = {
  foo: state => ({
    bar: state.foo.bar,
    baz: {
      bar: state.foo.baz.bar,
    },
  })
}
```

**Comment by edvincandon** [comment]
Alright seems fair ✌🏻

**Comment by edvincandon** [comment]
@brainlessdeveloper
Try it out: revux 1.2.0

**Comment by brainlessdeveloper** [comment]
Hey! Here's a sample: https://github.com/brainlessdeveloper/hackernews-ui/pull/7
It could get more verbose but now it can be abstracted more easily and it is consistent with `mapDispatch`.
