### ISSUE TITLE
Injection $$store not found

### ISSUE THREAD

**Issue by honghongzhou** [edvincandon/revux#10]
I don't know why the console gives the error that injection $$store not found.

**Comment by constant-flow** [comment]
@chenqunbing Maybe you didn't inject the store with the `<Provider>` tag, this will cause that error.

Like mentioned in the example for `main.vue` (sometimes `App.vue`):
`<Provider :store="store"> … </Provider>`

**Comment by edvincandon** [comment]
If that's not it - please provide some actual code :)
