### ISSUE TITLE
mapState function with access to props - feature request

### ISSUE THREAD

**Issue by KenticoMarianV** [edvincandon/revux#6]
Is it possible to add access to props in mapState like in react-redux
mapStateToProps(state, [ownProps]): stateProps
https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by edvincandon** [comment]
Seems quite appropriate 👍 

Once I merge the current PR I'll get it done !

**Comment by edvincandon** [comment]
merged - let me know if it suits your needs :)
